spring:
  datasource:
    url: jdbc:mysql://10.x.x.xx:xxx/eichong?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 80

mybatis:
  type-aliases-package: com.wanma.charge.domain
  mapper-locations: classpath:mapper/*.xml

